name: 'Nix Flakes'
description: 'Run Nix command with Flakes'
inputs:
  nix-cmd-args:
    description: 'Command arguments array to run with nix'
    required: false
    default: [ --help ]
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: ${{ inputs.nix-cmd-args }}
