name: 'Nix Flakes'
description: 'Run Nix command with Flakes'
inputs:
  nix-cmd:
    description: 'Command to run with nix'
    required: false
    default: --help
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: nix ${{ inputs.nix-cmd }}
