name: 'Nix Flakes'
description: 'Run Nix command with Flakes'
inputs:
  nix-cmds:
    description: 'Commands to run with sh -c $nix-cmds'
    required: false
    default: nix --help
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.nix-cmds }}
