name: 'Nix Flakes'
description: 'Run Nix command with Flakes'
inputs:
  nix-cmd:
    description: 'Command to run with sh -c nix $nix-cmd'
    required: false
    default: --help
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - nix ${{ inputs.nix-cmd }}
